services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistics-middleware-app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8080:8080"

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: logistics-middleware-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
